TAVILY_API_KEY="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"
OPENAI_API_KEY = "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"
HUGGINGFACEHUB_API_TOKEN = "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"
